// import './scripts/infoCollectionTranslate.tsx'
// import './scripts/todayOilPriceTranslate.tsx'
// import './scripts/monitorTranslate.tsx'
// import './scripts/infoCovid19Translate'
import './scripts/historyTranslate.tsx'
